### ISSUE TITLE
Joining to same survey does not work (Terms of service)

### ISSUE THREAD

**Issue by mwenell** [Webmie/WebView-and-WebExtension-2019#17]
PROBLEM

If you click (Android)  in profile New deal button -> give correct code -> check terms checkboxes -> click continue, then it hide the view and show only footer and nothing happens. it stops here.

**Comment by Njugen** [comment]
Suspicion: At this point, when clicking the "Coninue" button, the "Accept Tracking Deal" view gets hidden, and the UI starts to determine wether user is registered or not. As this process only returns 2 values to determine wether to run a registration or to run a join, i'd say this is not the problem.

The problem may lie in what happens identifying the user: when survey registration or survey joining happens. If either timeout or error from the server are returned as response -> user will see a blank screen with no views.

Solution:
A message modal has now been inserted into these 4 error cases. Should an error occur, the user will see this modal. The only button user may click is "Quit" button, which sends him back to the browser.

Codes visible in modal: 
- 101, any error returned from server when attempting to join
- 102, timeout error when attempting to join
- 103, any error returned from server when attempting to register
- 104, timeout error returned from server when attempting to register

Hopefully, the error that you encountered lied within these frames. If they happen, the user will now be guided out of it and asked to retry later or contact the service provider.
